# Ficheiro: .streamlit/secrets.toml

SUPABASE_URL = "https://woaabdetfcdhtygttshi.supabase.co"
SUPABASE_KEY = "sb_publishable_ucBogGEF7HSC2i3a6ey2rQ_hsquXLkY"
API_KEY = "8171043bf0a322286bb127947dbd4041" # A tua chave da API-Sports